spring:
  application:
    name: retroboy

app:
  config:
    globalConfig:
      esdeHome: 'D:\ES-DE\'
      raHome: 'D:\ES-DE\Emulators\RetroArch-Win64\'
      resourcesHome: 'D:\Resources\'
      globalTagBlacklist:
        - '3DS Virtual Console'
        - '8-bit Adventure Anthology - Volume I'
        - 'Animal Crossing'
        - 'Capcom Town'
        - 'Castlevania Anniversary Collection'
        - 'Contra Anniversary Collection'
        - 'e-Reader'
        - "Konami Collector's Series"
        - 'Limited Run Games'
        - 'Mega Man Legacy Collection'
        - 'Namcot Collection'
        - 'Namcot Collection, Namco Museum Archives Vol 1'
        - 'Namcot Collection, Namco Museum Archives Vol 2'
        - 'Namco Museum Archives Vol 1'
        - 'Namco Museum Archives Vol 2'
        - 'Retro-Bit Generations'
        - 'SNK 40th Anniversary Collection'
        - 'Test Program'
        - 'The Cowabunga Collection'
        - 'The Disney Afternoon Collection'
        - 'USA Wii Virtual Console, Wii U Virtual Console'
        - 'Virtual Console'
        - 'Wii U Virtual Console'
        - 'Wii Virtual Console'
        - 'Wii and Wii U Virtual Console'
    cleanUpTask:
      deleteFiles:
        - 'retroarch.cfg'
      deleteContentDirs:
        - 'info'
        - 'assets'
        - 'autoconfig'
        - 'cheats'
        - 'database'
        - 'overlays'
        - 'shaders'
        - 'cores'
        - 'system'
        - 'ROMs'
    defaultConfigTask:
      copyContentDirs:
        - srcDir: 'RetroArch-Win64\info'
          destDir: 'info'
        - srcDir: 'RetroArch-Win64\assets'
          destDir: 'assets'
        - srcDir: 'RetroArch-Win64\autoconfig'
          destDir: 'autoconfig'
        - srcDir: 'RetroArch-Win64\cheats'
          destDir: 'cheats'
        - srcDir: 'RetroArch-Win64\database'
          destDir: 'database'
        - srcDir: 'RetroArch-Win64\overlays'
          destDir: 'overlays'
        - srcDir: 'RetroArch-Win64\shaders'
          destDir: 'shaders'
        - srcDir: 'RetroArch-Win64\cores'
          destDir: 'cores'
        - srcDir: 'RetroArch-Win64\system'
          destDir: 'system'
        - srcDir: 'ROMs_ALL'
          destDir: 'ROMs'
      copyFiles:
        - srcFile: 'retroarch.cfg'
          destDir: ''
      raConfigs:
        - file: 'retroarch.cfg'
          key: 'video_fullscreen'
          value: 'true'
        - file: 'retroarch.cfg'
          key: 'rgui_browser_directory'
          value: 'ROMs'
        - file: 'retroarch.cfg'
          key: 'input_player1_analog_dpad_mode'
          value: '1'
    fixChineseFontTask:
      deleteFontFile: 'assets\pkg\chinese-fallback-font.ttf'
      copyFontFile:
        srcFile: 'chinese-fallback-font.ttf'
        destDir: 'assets\pkg'
      setNotificationFont:
        file: 'retroarch.cfg'
        key: 'video_font_path'
        value: ':\assets\pkg\chinese-fallback-font.ttf'
    setMegaBezelShaderTask:
      copyMegaBezelPacks:
        srcDir: 'Mega_Bezel_Packs'
        destDir: 'shaders'
      copyDefaultMegaBezelShader:
        - srcFile: 'global.slangp'
          destDir: 'config'
        - srcFile: 'retroarch.slangp'
          destDir: 'shaders'
      setMegaBezelShaderConfigs:
        - file: 'retroarch.cfg'
          key: 'video_driver'
          value: 'vulkan'
        - file: 'retroarch.cfg'
          key: 'aspect_ratio_index'
          value: '24'
        - file: 'retroarch.cfg'
          key: 'video_scale_integer'
          value: 'false'
        - file: 'retroarch.cfg'
          key: 'video_rotation'
          value: '0'
        - file: 'retroarch.cfg'
          key: 'video_allow_rotate'
          value: 'false'
        - file: 'retroarch.cfg'
          key: 'video_shader_enable'
          value: 'true'
    ruleConfigMap:
      NES:
        platform: 'NES'
        datFile: 'dats\Nintendo - Nintendo Entertainment System.dat'
        romDir: 'roms\nes'
        targetDirBase: 'ROMs\nes'
        targetAreaConfigs:
          - area: 'JPN'
          - area: 'USA'
          - area: 'EUR'
        tagBlackList: [ ]
        fileNameBlackList: [ ]