spring:
  application:
    name: retroboy

app:
  config:
    cleanup:
      cleanupDirs:
        - 'D:\ES-DE\Emulators\RetroArch-Win64\info' # 核心信息文件
        - 'D:\ES-DE\Emulators\RetroArch-Win64\assets' # 素材
        - 'D:\ES-DE\Emulators\RetroArch-Win64\autoconfig' # 手柄配置
        - 'D:\ES-DE\Emulators\RetroArch-Win64\cheats' # 金手指
        - 'D:\ES-DE\Emulators\RetroArch-Win64\database' # 数据库
        - 'D:\ES-DE\Emulators\RetroArch-Win64\overlays' # 遮罩
        - 'D:\ES-DE\Emulators\RetroArch-Win64\shaders' # 着色器
        - 'D:\ES-DE\Emulators\RetroArch-Win64\cores' # 核心
        - 'D:\ES-DE\Emulators\RetroArch-Win64\system' # BIOS
        - 'D:\ES-DE\ROMs' # ROMs
      deleteDirs:
        - ''
      deleteFiles:
        - 'D:\ES-DE\Emulators\RetroArch-Win64\retroarch.cfg' # RA默认配置文件
    copyDefault:
      copyDirs:
        - src: 'D:\Resources\RetroArch-Win64\info'
          dest: 'D:\ES-DE\Emulators\RetroArch-Win64\info'
        - src: 'D:\Resources\RetroArch-Win64\assets'
          dest: 'D:\ES-DE\Emulators\RetroArch-Win64\assets'
        - src: 'D:\Resources\RetroArch-Win64\autoconfig'
          dest: 'D:\ES-DE\Emulators\RetroArch-Win64\autoconfig'
        - src: 'D:\Resources\RetroArch-Win64\cheats'
          dest: 'D:\ES-DE\Emulators\RetroArch-Win64\cheats'
        - src: 'D:\Resources\RetroArch-Win64\database'
          dest: 'D:\ES-DE\Emulators\RetroArch-Win64\database'
        - src: 'D:\Resources\RetroArch-Win64\overlays'
          dest: 'D:\ES-DE\Emulators\RetroArch-Win64\overlays'
        - src: 'D:\Resources\RetroArch-Win64\shaders'
          dest: 'D:\ES-DE\Emulators\RetroArch-Win64\shaders'
        - src: 'D:\Resources\RetroArch-Win64\cores'
          dest: 'D:\ES-DE\Emulators\RetroArch-Win64\cores'
        - src: 'D:\Resources\RetroArch-Win64\system'
          dest: 'D:\ES-DE\Emulators\RetroArch-Win64\system'
        - src: 'D:\ES-DE\ROMs_ALL'
          dest: 'D:\ES-DE\ROMs'
      copyFiles:
        - srcFile: 'D:\Resources\retroarch.cfg'
          destDir: 'D:\ES-DE\Emulators\RetroArch-Win64'
    configDefault:
      retroArchConfigs:
        - configFile: 'D:\ES-DE\Emulators\RetroArch-Win64\retroarch.cfg'
          key: 'video_fullscreen'
          value: 'true'
        - configFile: 'D:\ES-DE\Emulators\RetroArch-Win64\retroarch.cfg'
          key: 'rgui_browser_directory'
          value: 'D:\ES-DE\ROMs'
        - configFile: 'D:\ES-DE\Emulators\RetroArch-Win64\retroarch.cfg'
          key: 'input_player1_analog_dpad_mode'
          value: '1'
    retroArchConfig: 'D:\ES-DE\Emulators\RetroArch-Win64\retroarch.cfg'