spring:
  application:
    name: retroboy

app:
  config:
    globalConfig:
      raConfigFile: 'D:\ES-DE\Emulators\RetroArch-Win64\retroarch.cfg'
      tagBlacklist:
        - '3DS Virtual Console'
        - '8-bit Adventure Anthology - Volume I'
        - 'Animal Crossing'
        - 'Capcom Town'
        - 'Castlevania Anniversary Collection'
        - 'Contra Anniversary Collection'
        - 'e-Reader'
        - "Konami Collector's Series"
        - 'Limited Run Games'
        - 'Mega Man Legacy Collection'
        - 'Namcot Collection'
        - 'Namcot Collection, Namco Museum Archives Vol 1'
        - 'Namcot Collection, Namco Museum Archives Vol 2'
        - 'Namco Museum Archives Vol 1'
        - 'Namco Museum Archives Vol 2'
        - 'Retro-Bit Generations'
        - 'SNK 40th Anniversary Collection'
        - 'Test Program'
        - 'The Cowabunga Collection'
        - 'The Disney Afternoon Collection'
        - 'USA Wii Virtual Console, Wii U Virtual Console'
        - 'Virtual Console'
        - 'Wii U Virtual Console'
        - 'Wii Virtual Console'
        - 'Wii and Wii U Virtual Console'
    cleanUpTask:
      deleteDirs: []
      deleteFiles:
        - 'D:\ES-DE\Emulators\RetroArch-Win64\retroarch.cfg'
      deleteContentDirs:
        - 'D:\ES-DE\Emulators\RetroArch-Win64\info'
        - 'D:\ES-DE\Emulators\RetroArch-Win64\assets'
        - 'D:\ES-DE\Emulators\RetroArch-Win64\autoconfig'
        - 'D:\ES-DE\Emulators\RetroArch-Win64\cheats'
        - 'D:\ES-DE\Emulators\RetroArch-Win64\database'
        - 'D:\ES-DE\Emulators\RetroArch-Win64\overlays'
        - 'D:\ES-DE\Emulators\RetroArch-Win64\shaders'
        - 'D:\ES-DE\Emulators\RetroArch-Win64\cores'
        - 'D:\ES-DE\Emulators\RetroArch-Win64\system'
        - 'D:\ES-DE\ROMs'
    defaultConfigTask:
      copyContentDirs:
        - srcDir: 'D:\Resources\RetroArch-Win64\info'
          destDir: 'D:\ES-DE\Emulators\RetroArch-Win64\info'
        - srcDir: 'D:\Resources\RetroArch-Win64\assets'
          destDir: 'D:\ES-DE\Emulators\RetroArch-Win64\assets'
        - srcDir: 'D:\Resources\RetroArch-Win64\autoconfig'
          destDir: 'D:\ES-DE\Emulators\RetroArch-Win64\autoconfig'
        - srcDir: 'D:\Resources\RetroArch-Win64\cheats'
          destDir: 'D:\ES-DE\Emulators\RetroArch-Win64\cheats'
        - srcDir: 'D:\Resources\RetroArch-Win64\database'
          destDir: 'D:\ES-DE\Emulators\RetroArch-Win64\database'
        - srcDir: 'D:\Resources\RetroArch-Win64\overlays'
          destDir: 'D:\ES-DE\Emulators\RetroArch-Win64\overlays'
        - srcDir: 'D:\Resources\RetroArch-Win64\shaders'
          destDir: 'D:\ES-DE\Emulators\RetroArch-Win64\shaders'
        - srcDir: 'D:\Resources\RetroArch-Win64\cores'
          destDir: 'D:\ES-DE\Emulators\RetroArch-Win64\cores'
        - srcDir: 'D:\Resources\RetroArch-Win64\system'
          destDir: 'D:\ES-DE\Emulators\RetroArch-Win64\system'
        - srcDir: 'D:\ES-DE\ROMs_ALL'
          destDir: 'D:\ES-DE\ROMs'
      copyFiles:
        - srcFile: 'D:\Resources\retroarch.cfg'
          destDir: 'D:\ES-DE\Emulators\RetroArch-Win64'
      raConfigs:
        - file: 'D:\ES-DE\Emulators\RetroArch-Win64\retroarch.cfg'
          key: 'video_fullscreen'
          value: 'true'
        - file: 'D:\ES-DE\Emulators\RetroArch-Win64\retroarch.cfg'
          key: 'rgui_browser_directory'
          value: 'D:\ES-DE\ROMs'
        - file: 'D:\ES-DE\Emulators\RetroArch-Win64\retroarch.cfg'
          key: 'input_player1_analog_dpad_mode'
          value: '1'
    fixChineseFontTask:
      deleteFontFile: 'D:\ES-DE\Emulators\RetroArch-Win64\assets\pkg\chinese-fallback-font.ttf'
      copyFontFile:
        srcFile: 'D:\Resources\chinese-fallback-font.ttf'
        destDir: 'D:\ES-DE\Emulators\RetroArch-Win64\assets\pkg'
      setNotificationFont:
        file: 'D:\ES-DE\Emulators\RetroArch-Win64\retroarch.cfg'
        key: 'video_font_path'
        value: ':\assets\pkg\chinese-fallback-font.ttf'
    setMegaBezelShaderTask:
      copyMegaBezelPacks:
        srcDir: 'D:\Resources\Mega_Bezel_Packs'
        destDir: 'D:\ES-DE\Emulators\RetroArch-Win64\shaders'
      copyDefaultMegaBezelShader:
        - srcFile: 'D:\Resources\global.slangp'
          destDir: 'D:\ES-DE\Emulators\RetroArch-Win64\config'
        - srcFile: 'D:\Resources\retroarch.slangp'
          destDir: 'D:\ES-DE\Emulators\RetroArch-Win64\shaders'
      setMegaBezelShaderConfigs:
        - file: 'D:\ES-DE\Emulators\RetroArch-Win64\retroarch.cfg'
          key: 'video_driver'
          value: 'vulkan'
        - file: 'D:\ES-DE\Emulators\RetroArch-Win64\retroarch.cfg'
          key: 'aspect_ratio_index'
          value: '24'
        - file: 'D:\ES-DE\Emulators\RetroArch-Win64\retroarch.cfg'
          key: 'video_scale_integer'
          value: 'false'
        - file: 'D:\ES-DE\Emulators\RetroArch-Win64\retroarch.cfg'
          key: 'video_rotation'
          value: '0'
        - file: 'D:\ES-DE\Emulators\RetroArch-Win64\retroarch.cfg'
          key: 'video_allow_rotate'
          value: 'false'
        - file: 'D:\ES-DE\Emulators\RetroArch-Win64\retroarch.cfg'
          key: 'video_shader_enable'
          value: 'true'
    ruleConfigs:
      - platform: 'nes'
        datFile: 'D:\Resources\dats\Nintendo - Nintendo Entertainment System.dat'
        romDir: 'D:\Resources\roms\nes'
        targetDirBase: 'D:\ES-DE\ROMs\nes'
        targetAreaConfigs:
          - area: 'JPN'
          - area: 'USA'
          - area: 'EUR'