spring:
  application:
    name: retroboy

app:
  config:
    globalConfig:
      raMainConfig: 'D:\ES-DE\Emulators\RetroArch-Win64\retroarch.cfg'
    cleanUpTask:
      deleteDirs: []
      deleteFiles:
        - 'D:\ES-DE\Emulators\RetroArch-Win64\retroarch.cfg'
      deleteContentDirs:
        - 'D:\ES-DE\Emulators\RetroArch-Win64\info'
        - 'D:\ES-DE\Emulators\RetroArch-Win64\assets'
        - 'D:\ES-DE\Emulators\RetroArch-Win64\autoconfig'
        - 'D:\ES-DE\Emulators\RetroArch-Win64\cheats'
        - 'D:\ES-DE\Emulators\RetroArch-Win64\database'
        - 'D:\ES-DE\Emulators\RetroArch-Win64\overlays'
        - 'D:\ES-DE\Emulators\RetroArch-Win64\shaders'
        - 'D:\ES-DE\Emulators\RetroArch-Win64\cores'
        - 'D:\ES-DE\Emulators\RetroArch-Win64\system'
        - 'D:\ES-DE\ROMs'
    defaultConfigTask:
      copyContentDirs:
        - srcDirPath: 'D:\Resources\RetroArch-Win64\info'
          destDirPath: 'D:\ES-DE\Emulators\RetroArch-Win64\info'
        - srcDirPath: 'D:\Resources\RetroArch-Win64\assets'
          destDirPath: 'D:\ES-DE\Emulators\RetroArch-Win64\assets'
        - srcDirPath: 'D:\Resources\RetroArch-Win64\autoconfig'
          destDirPath: 'D:\ES-DE\Emulators\RetroArch-Win64\autoconfig'
        - srcDirPath: 'D:\Resources\RetroArch-Win64\cheats'
          destDirPath: 'D:\ES-DE\Emulators\RetroArch-Win64\cheats'
        - srcDirPath: 'D:\Resources\RetroArch-Win64\database'
          destDirPath: 'D:\ES-DE\Emulators\RetroArch-Win64\database'
        - srcDirPath: 'D:\Resources\RetroArch-Win64\overlays'
          destDirPath: 'D:\ES-DE\Emulators\RetroArch-Win64\overlays'
        - srcDirPath: 'D:\Resources\RetroArch-Win64\shaders'
          destDirPath: 'D:\ES-DE\Emulators\RetroArch-Win64\shaders'
        - srcDirPath: 'D:\Resources\RetroArch-Win64\cores'
          destDirPath: 'D:\ES-DE\Emulators\RetroArch-Win64\cores'
        - srcDirPath: 'D:\Resources\RetroArch-Win64\system'
          destDirPath: 'D:\ES-DE\Emulators\RetroArch-Win64\system'
        - srcDirPath: 'D:\ES-DE\ROMs_ALL'
          destDirPath: 'D:\ES-DE\ROMs'
      copyFiles:
        - srcFile: 'D:\Resources\retroarch.cfg'
          destDir: 'D:\ES-DE\Emulators\RetroArch-Win64'
      raConfigs:
        - configFile: 'D:\ES-DE\Emulators\RetroArch-Win64\retroarch.cfg'
          key: 'video_fullscreen'
          value: 'true'
        - configFile: 'D:\ES-DE\Emulators\RetroArch-Win64\retroarch.cfg'
          key: 'rgui_browser_directory'
          value: 'D:\ES-DE\ROMs'
        - configFile: 'D:\ES-DE\Emulators\RetroArch-Win64\retroarch.cfg'
          key: 'input_player1_analog_dpad_mode'
          value: '1'
    fixChineseFontTask:
      deleteFontFile: 'D:\ES-DE\Emulators\RetroArch-Win64\assets\pkg\chinese-fallback-font.ttf'
      copyFontFile:
        srcFilePath: 'D:\Resources\chinese-fallback-font.ttf'
        destDirPath: 'D:\ES-DE\Emulators\RetroArch-Win64\assets\pkg'
      setNotificationFont:
        configFile: 'D:\ES-DE\Emulators\RetroArch-Win64\retroarch.cfg'
        key: 'video_font_path'
        value: ':\assets\pkg\chinese-fallback-font.ttf'
    globalTagBlackList:
      - '3DS Virtual Console'
      - '8-bit Adventure Anthology - Volume I'
      - 'Animal Crossing'
      - 'Capcom Town'
      - 'Castlevania Anniversary Collection'
      - 'Contra Anniversary Collection'
      - 'e-Reader'
      - "Konami Collector's Series"
      - 'Limited Run Games'
      - 'Mega Man Legacy Collection'
      - 'Namcot Collection'
      - 'Namcot Collection, Namco Museum Archives Vol 1'
      - 'Namcot Collection, Namco Museum Archives Vol 2'
      - 'Namco Museum Archives Vol 1'
      - 'Namco Museum Archives Vol 2'
      - 'Retro-Bit Generations'
      - 'SNK 40th Anniversary Collection'
      - 'Test Program'
      - 'The Cowabunga Collection'
      - 'The Disney Afternoon Collection'
      - 'USA Wii Virtual Console, Wii U Virtual Console'
      - 'Virtual Console'
      - 'Wii U Virtual Console'
      - 'Wii Virtual Console'
      - 'Wii and Wii U Virtual Console'
    nesRuleConfig:
      datFile: 'D:\Resources\dats\Nintendo - Nintendo Entertainment System.dat'
      romDir: 'D:\Resources\roms\nes'
      japanTargetDir: 'D:\ES-DE\ROMs\nes\JPN'
      usaTargetDir: 'D:\ES-DE\ROMs\nes\USA'
      europeTargetDir: 'D:\ES-DE\ROMs\nes\EUR'