spring:
  application:
    name: retroboy

app:
  config:
    cleanup:
      cleanupDirs:
        - 'D:\ES-DE\Emulators\RetroArch-Win64\info' # 核心信息文件
        - 'D:\ES-DE\Emulators\RetroArch-Win64\assets' # 素材
        - 'D:\ES-DE\Emulators\RetroArch-Win64\autoconfig' # 手柄配置
        - 'D:\ES-DE\Emulators\RetroArch-Win64\cheats' # 金手指
        - 'D:\ES-DE\Emulators\RetroArch-Win64\database' # 数据库
        - 'D:\ES-DE\Emulators\RetroArch-Win64\overlays' # 遮罩
        - 'D:\ES-DE\Emulators\RetroArch-Win64\shaders' # 着色器
        - 'D:\ES-DE\Emulators\RetroArch-Win64\cores' # 核心
        - 'D:\ES-DE\Emulators\RetroArch-Win64\system' # BIOS
        - 'D:\ES-DE\ROMs' # ROMs
      deleteDirs:
        - ''
      deleteFiles:
        - 'D:\ES-DE\Emulators\RetroArch-Win64\retroarch.cfg' # RA默认配置文件
    copyDefault:
      copyDirs:
        - src: 'D:\Resources\RetroArch-Win64\info'
          dest: 'D:\ES-DE\Emulators\RetroArch-Win64\info'
        - src: 'D:\Resources\RetroArch-Win64\assets'
          dest: 'D:\ES-DE\Emulators\RetroArch-Win64\assets'
        - src: 'D:\Resources\RetroArch-Win64\autoconfig'
          dest: 'D:\ES-DE\Emulators\RetroArch-Win64\autoconfig'
        - src: 'D:\Resources\RetroArch-Win64\cheats'
          dest: 'D:\ES-DE\Emulators\RetroArch-Win64\cheats'
        - src: 'D:\Resources\RetroArch-Win64\database'
          dest: 'D:\ES-DE\Emulators\RetroArch-Win64\database'
        - src: 'D:\Resources\RetroArch-Win64\overlays'
          dest: 'D:\ES-DE\Emulators\RetroArch-Win64\overlays'
        - src: 'D:\Resources\RetroArch-Win64\shaders'
          dest: 'D:\ES-DE\Emulators\RetroArch-Win64\shaders'
        - src: 'D:\Resources\RetroArch-Win64\cores'
          dest: 'D:\ES-DE\Emulators\RetroArch-Win64\cores'
        - src: 'D:\Resources\RetroArch-Win64\system'
          dest: 'D:\ES-DE\Emulators\RetroArch-Win64\system'
        - src: 'D:\ES-DE\ROMs_ALL'
          dest: 'D:\ES-DE\ROMs'
      copyFiles:
        - srcFile: 'D:\Resources\retroarch.cfg'
          destDir: 'D:\ES-DE\Emulators\RetroArch-Win64'
    configDefault:
      retroArchConfigs:
        - configFile: 'D:\ES-DE\Emulators\RetroArch-Win64\retroarch.cfg'
          key: 'video_fullscreen'
          value: 'true'
        - configFile: 'D:\ES-DE\Emulators\RetroArch-Win64\retroarch.cfg'
          key: 'rgui_browser_directory'
          value: 'D:\ES-DE\ROMs'
        - configFile: 'D:\ES-DE\Emulators\RetroArch-Win64\retroarch.cfg'
          key: 'input_player1_analog_dpad_mode'
          value: '1'
    retroArchConfig: 'D:\ES-DE\Emulators\RetroArch-Win64\retroarch.cfg'
    globalTagBlackList:
      - '3DS Virtual Console'
      - '8-bit Adventure Anthology - Volume I'
      - 'Animal Crossing'
      - 'Capcom Town'
      - 'Castlevania Anniversary Collection'
      - 'Contra Anniversary Collection'
      - 'e-Reader'
      - "Konami Collector's Series"
      - 'Limited Run Games'
      - 'Mega Man Legacy Collection'
      - 'Namcot Collection'
      - 'Namcot Collection, Namco Museum Archives Vol 1'
      - 'Namcot Collection, Namco Museum Archives Vol 2'
      - 'Namco Museum Archives Vol 1'
      - 'Namco Museum Archives Vol 2'
      - 'Retro-Bit Generations'
      - 'SNK 40th Anniversary Collection'
      - 'Test Program'
      - 'The Cowabunga Collection'
      - 'The Disney Afternoon Collection'
      - 'USA Wii Virtual Console, Wii U Virtual Console'
      - 'Virtual Console'
      - 'Wii U Virtual Console'
      - 'Wii Virtual Console'
      - 'Wii and Wii U Virtual Console'
    nesRuleConfig:
      datFile: 'D:\Resources\dats\Nintendo - Nintendo Entertainment System.dat'
      romDir: 'D:\Resources\roms\nes'
      japanTargetDir: 'D:\ES-DE\ROMs\nes\JPN'
      usaTargetDir: 'D:\ES-DE\ROMs\nes\USA'
      europeTargetDir: 'D:\ES-DE\ROMs\nes\EUR'